INSERT INTO roles (name) SELECT  'USER' WHERE NOT EXISTS ( SELECT name FROM roles WHERE name = 'USER');

INSERT INTO roles (name) SELECT  'MODERATOR' WHERE NOT EXISTS ( SELECT name FROM roles WHERE name = 'MODERATOR');

INSERT INTO roles (name) SELECT  'ADMIN' WHERE NOT EXISTS ( SELECT name FROM roles WHERE name = 'ADMIN');

